spring:
  mvc.view.prefix: /WEB-INF/jsps/
  mvc.view.suffix: .jsp

server:
  port: 8084

amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXX
  secretKey: XXXXX
  bucketName: file-uploaded-bucket
  region: us-east-2